### PR TITLE
added stub for Bootstrap renderer config

### PR DESCRIPTION
**Pull request by mtymek**
Without this lines in module config, it gives following notice:

Notice: Undefined index: ReverseForm\Renderer\Bootstrap in /home/mat/public_html/whatever/vendor/silvester/reverse-form/src/ReverseForm/Renderer.php on line 286

### CODE REVIEW

**Comment by silvester** [comment]
I would rather check if array key exists then adding a stub, what do you think?

``` php
if(array_key_exists(get_class($this), $this->globalFormConfig)) {
    $this->localConfig = $this->globalFormConfig[get_class($this)];
}
```

Another option I am thinking about is implementing Zend\Stdlib\AbstractOptions to the renderer object which would give more flexibility.

**Comment by mtymek** [comment]
Indeed, checking for array key looks nicer - I will update this PR.
Can't say much for AbstractOptions. IMO it's not worth the effort. I dived into ZF sources, and it looks like they're using AbstractOptions only when they want to add extra validation of config variables.

**Comment by silvester** [comment]
you still have to remove the next line after the if statement.

Lp. Silvester

**Comment by mtymek** [comment]
Totally missed that :-)

**Pull request merged**
