### PR TITLE
Fix checkbox tpl rendering

### PR DESCRIPTION
**Pull request by seyfer**
Fix error from issue https://github.com/silvester/ReverseForm/issues/11

### CODE REVIEW

**Comment by seyfer** [comment]
@silvester now you see, it's not hard to fix.

About formation - my version was more readalble. But i'm fix it back.

**Comment by seyfer** [comment]
@silvester Can you please accept my pull request?

**Comment by silvester** [comment]
Thanks.

**Comment by mdjaman** [comment]
No thanks it doesn't work regular way.

``` php
$sexe = new Element\Radio('sexe');
$sexe->setLabel('Sexe');
$sexe->setValueOptions(array(
            //array(
                'M' => 'M',
                'F' => 'F'
            //),
));
$sexe->setUseHiddenElement(true)
         ->setValue("M");
```

Warning: Invalid argument supplied for foreach() 
and no radio display. It works when i switch back LINE 24 to $e->getOption('value_options')
in addition to zf2 array notation like you do in TestForm.php script.
Please review.

**Comment by seyfer** [comment]
@mdjaman 
what version of ZF2 you use? in latest 2.2 version it's work like in my fix, and don't work in old way.
so, you need update your ZF2 or make pull which fix for both versions.

**Comment by mdjaman** [comment]
@seyfer i use 2.2.5

**Pull request merged**
